"""ShopMind security boundary contracts."""

from .audit import (
    GOVERNANCE_AUDIT_SCHEMA_VERSION,
    AuditActorKind,
    AuditCategory,
    AuditDecision,
    AuditDeletionTarget,
    AuditFingerprintNamespace,
    AuditOperation,
    AuditReason,
    AuditRequestOperation,
    GovernanceAuditFactory,
    GovernanceAuditMetadata,
    GovernanceAuditRecord,
    governance_fingerprint,
)
from .identity import (
    AuthenticatedPrincipal,
    AuthenticationRequiredError,
    AuthorizationDeniedError,
    IdentityAuthenticationFailure,
    IdentityBinding,
    IdentityBoundary,
    IdentityProviderName,
    SIGNED_IDENTITY_SCHEMA_VERSION,
    SignedHeaderIdentityVerifier,
    SignedIdentityVerification,
    build_identity_boundary,
    signed_identity_signature,
)

__all__ = [
    "GOVERNANCE_AUDIT_SCHEMA_VERSION",
    "AuditActorKind",
    "AuditCategory",
    "AuditDecision",
    "AuditDeletionTarget",
    "AuditFingerprintNamespace",
    "AuditOperation",
    "AuditReason",
    "AuditRequestOperation",
    "AuthenticatedPrincipal",
    "AuthenticationRequiredError",
    "AuthorizationDeniedError",
    "IdentityAuthenticationFailure",
    "IdentityBinding",
    "IdentityBoundary",
    "IdentityProviderName",
    "SIGNED_IDENTITY_SCHEMA_VERSION",
    "SignedHeaderIdentityVerifier",
    "SignedIdentityVerification",
    "GovernanceAuditFactory",
    "GovernanceAuditMetadata",
    "GovernanceAuditRecord",
    "build_identity_boundary",
    "governance_fingerprint",
    "signed_identity_signature",
]
